### ISSUE TITLE
Clarify the license

### ISSUE THREAD

**Issue by bbatsov** [flycheck/flycheck-eglot#4]
I've noticed that the source has both GPL and MIT in its header. Is it supposed to be dual-licensed or is this an oversight?

Might be a good idea add a "License" section in the README.

**Comment by intramurz** [comment]
Yes, I have already thought about this question. The starting point was code under the MIT license, as mentioned in the source header. Since then, most of the code has been added and modified, but some remains from the original version. As far as I know, MIT-licensed code can be used in any way as long as the original license is credited, including re-licensing under the GPL, but maybe I'm wrong.

I consider the project to be GPL 3rd licensed, as stated by the source header and LICENSE file. Dual licensing in this case makes no sense and is misleading. If there are suggestions on how to deal with the above situation, I will try to follow them.

**Comment by intramurz** [comment]
Thank you for refining the documentation. I couldn't get around to figuring it out :confused:
