### ISSUE TITLE
flycheck-mode doesn't immediately check errors when the file is opened

### ISSUE THREAD

**Issue by IceAsteroid** [flycheck/flycheck-eglot#5]
The first time, the file is opened, doesn't display flycheck errors in eglot.

It needs to start editing the buffer to show flycheck errors.

Flymake works fine. It shows errors when the file is first opened in eglot.

**Comment by intramurz** [comment]
Hi!

Could you please clarify which compiler/environment you're having trouble with? I made several small experiments: introduce an error into the code, save the file, kill the buffer, restart Emacs, open the file, look at the list of errors. I only experimented with tools that I use myself. For c/c++ (clangd) and python (pylsp), the error is detected immediately upon opening, everything is fine. Flycheck and eglot settings are default (more or less). Things are getting worse for rust, but the problem seems to be more in the design of rust (and rust-analyser) itself.

**Comment by IceAsteroid** [comment]
Sorry for not responding after a long time, I was switching to flymake since elgot natively supports, now I'm switching back and finally discovered this issue again. 

It turns out that it was caused by my configuration, I set up the read-only-mode to be added to the `find-file-hook' hook.

I was just starting Emacs back then. It was a poor implementation to the feature I wanted, has been causing lots of issues in Emacs, and making often me often have to write additional workarounds for it.

Having that `read-only-mode` when opening a file stuff removed from the init file solves the problem.

Sorry for the noise. Have good days!

**Comment by IceAsteroid** [comment]
Maybe it can be solved natively with `(inhibit-read-only t)` for flycheck, which is what I often implement the workaround for particular commands that write to buffers which are in `read-only-mode`.

**Comment by intramurz** [comment]
> Sorry for not responding after a long time, I was switching to flymake since elgot natively supports, now I'm switching back and finally discovered this issue again.
> 
> It turns out that it was caused by my configuration, I set up the `read-only-mode` to be added to the `find-file-hook` hook.
> 
> I was just starting Elisp back then. It was a poor implementation to the feature I wanted, has been causing lots of issues in Emacs, and making me often have to write additional workarounds for it.
> 
> Having that `read-only-mode` stuff in the `find-file-hook` removed from the init file solves the problem.
> 
> Sorry for the noise. Have good days!

Thank you. Good luck.
